### ISSUE TITLE
Continue adding agents until we have sufficient coverage

### ISSUE THREAD

**Issue by haikalpribadi** [vaticle/typedb-benchmark#29]

**Comment by lolski** [comment]
I'm moving this issue from "In progress" to "TODO". The reason is that as of https://github.com/graknlabs/simulation/commit/c5edff018df75d96300c70bcc667f38570b389b0, the current agents already provides enough coverage, and the bottleneck is more on being able to display the simulation data on Grabl.

**Comment by jmsfltchr** [comment]
Now tracked here https://github.com/vaticle/typedb-benchmark/issues/127 and here https://github.com/vaticle/typedb-benchmark/issues/39
